
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __AGENT_ENUM_TYPES_H__
#define __AGENT_ENUM_TYPES_H__ 1

#include <glib-object.h>

G_BEGIN_DECLS
/* enumerations from "./agent.h" */
GType nice_component_state_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_COMPONENT_STATE (nice_component_state_get_type())
GType nice_component_type_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_COMPONENT_TYPE (nice_component_type_get_type())
GType nice_compatibility_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_COMPATIBILITY (nice_compatibility_get_type())
GType nice_proxy_type_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_PROXY_TYPE (nice_proxy_type_get_type())
GType nice_nomination_mode_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_NOMINATION_MODE (nice_nomination_mode_get_type())
GType nice_agent_option_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_AGENT_OPTION (nice_agent_option_get_type())
/* enumerations from "./candidate.h" */
GType nice_candidate_type_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_CANDIDATE_TYPE (nice_candidate_type_get_type())
GType nice_candidate_transport_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_CANDIDATE_TRANSPORT (nice_candidate_transport_get_type())
GType nice_relay_type_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_RELAY_TYPE (nice_relay_type_get_type())
/* enumerations from "./pseudotcp.h" */
GType pseudo_tcp_debug_level_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_TCP_DEBUG_LEVEL (pseudo_tcp_debug_level_get_type())
GType pseudo_tcp_state_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_TCP_STATE (pseudo_tcp_state_get_type())
GType pseudo_tcp_write_result_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_TCP_WRITE_RESULT (pseudo_tcp_write_result_get_type())
GType pseudo_tcp_shutdown_get_type (void) G_GNUC_CONST;
#define NICE_TYPE_TCP_SHUTDOWN (pseudo_tcp_shutdown_get_type())
G_END_DECLS

#endif /* !AGENT_ENUM_TYPES_H */

/* Generated data ends here */

